apiVersion: v2
description: FMTOK8s Agenda Service Helm chart for Kubernetes
name: fmtok8s-agenda-service
version: 0.1.0
icon: https://salaboy.files.wordpress.com/2019/07/avatar.png
dependencies:
- name: redis
  version: 17.6.0 
  repository: https://charts.bitnami.com/bitnami
  condition: redis.enabled
