apiVersion: v2
description: FMTOK8s Agenda Service (REST) Helm chart for Kubernetes
name: fmtok8s-agenda-rest
version: 0.0.10
icon: https://raw.githubusercontent.com/cdfoundation/artwork/master/jenkinsx/icon/color/jenkinsx-icon-color.png
